Remove javax from default excluded packages
scalameta/metals pull request #2091
Opened 2020-09-23 19:29 UTC by gabro

Closes #2090

As discussed in the issue, the exclusion of javax isn't probably a great default anymore.
We even use some javax imports ourselves in Metals!

This PR removes `javax` from the default set of excluded packages. Users can opt-in to the exclusion using the recently released setting.

2020-09-23 19:30 UTC, gabro commented on metals/src/main/scala/scala/meta/internal/metals/UserConfiguration.scala
> +            |["--sun"]
I've picked another example, since javax is not excluded anymore

2020-09-23 19:43 UTC, olafurpg approved these changes
LGTM :+1: I can't remember the exact reason `javax/` was excluded by default but I think it just contained some generic class names that frequently conflicted with symbols that I was working with in the Metals codebase in the early days. I don't mind including it by default

2020-09-23 20:03 UTC, ckipp01 approved these changes
Looks good! LGTM!

2020-09-24 08:47 UTC, tgodzik requested changes
Thanks for following up on the issue! There are some tests still failing, but it seems they are all connected to the changes.

2020-09-25 10:35 UTC, tgodzik approved these changes
LGTM!

2020-09-25 10:35 UTC, merged