Fix #2106: Sbt completions fix
scalameta/metals pull request #2129
Opened 2020-10-09 13:51 UTC by dos65

I tested it locally but I'm if it's possible to write a test on this thing.

I tried to comment [this line in SbtLspSuite](https://github.com/scalameta/metals/blob/73ac12e4d4b8f4146db0524c63e78ca960fe4bb9/tests/slow/src/test/scala/tests/sbt/SbtLspSuite.scala#L578) but it doesn't work

2020-10-09 14:12 UTC, tgodzik commented
Thanks for the contribution! Out of curiosity, what is the case it solves?

2020-10-09 16:53 UTC, tgodzik commented
> This issue - [#2106 Completions from sbt's Scala files only available after opening them ](https://github.com/scalameta/metals/issues/2106)
> 
> As I got, `didOpen` calls `Compilations.compileFile` that should trigger compilation of buildTarget.
> 
> Without this fix, `expand` doesn't return buildTarget for `build.sbt` and that why nothing works until any of scala sources from meta build will be opened in the editor.

Sorry, haven't noticed that it's in the title :sweat_smile: A bit under the weather today. I will take a look at it a bit closer probably tomorrow or monday. Again, thanks for the contribution!

2020-10-14 17:19 UTC, dos65 commented
@tgodzik Thx! It works with `server.didOpen("build.sbt")`.

However,  this test produces some error message in the log about `MetaValues.scala.sematicdb` file existence.
I will try to fix it and update PR.

2020-10-15 08:54 UTC, tgodzik commented
> @tgodzik Thx! It works with `server.didOpen("build.sbt")`.
> 
> However, this test produces some error message in the log about `MetaValues.scala.sematicdb` file existence.
> I will try to fix it and update PR.

We might just ignore those in sbt build files for now as the semanticdb files are not expected to be there currently.

2020-10-15 12:17 UTC, dos65 commented
@tgodzik Ok. Added your test

2020-10-15 12:22 UTC, tgodzik requested changes
Thanks! We should be good to merge if you could remove the additional println?

2020-10-15 12:22 UTC, tgodzik commented on tests/slow/src/test/scala/tests/sbt/SbtLspSuite.scala
> +      _ = println("DONE")
Could you just remove the `println`?

2020-10-15 12:41 UTC, dos65 commented on tests/slow/src/test/scala/tests/sbt/SbtLspSuite.scala
> +      _ = println("DONE")
Ough. Sorry - done

2020-10-15 14:21 UTC, tgodzik approved these changes
LGTM!

2020-10-15 14:22 UTC, merged