Update to Docusaurus 2.0
scalameta/metals pull request #2927
Opened 2021-07-03 16:03 UTC by ckipp01

So there are a bunch of changes here and I still need to update a last few things.

- [ ] Clean up dead links
- [ ] Make sure full blog is there on build

Just to give a brief overview, taken from the Docusaurus website:

> Docusaurus v2 is beta but already quite stable and widely used.

> We highly encourage you to use Docusaurus v2 over Docusaurus v1, as Docusaurus v1 will be deprecated soon.

> A lot of users are already using Docusaurus v2 (trends).

> Use Docusaurus v2 if:

> ✅ You want a modern Jamstack documentation site
> ✅ You want a single-page application (SPA) with client-side routing
> ✅ You want the full power of React and MDX
> ✅ You do not need support for IE11
> Use Docusaurus v1 if:

> ❌ You don't want a single-page application (SPA)
> ❌ You need support for IE11

I also did this migration partially with their [migration-helper](https://docusaurus.io/docs/migration/automated), but there ended up being a pretty large chunk that needed to be done manually.

I published a temp version of the site at [https://metals-test-ckipp01.vercel.app/](https://metals-test-ckipp01.vercel.app/) so feel free to poke around and let me know what you think.

2021-07-05 11:47 UTC, tgodzik requested changes
Thanks for working on this! Looks pretty neat. I have some doubts about:

![image](https://user-images.githubusercontent.com/3807253/124466966-7f459980-dd97-11eb-82b8-6208b13f079f.png)

O we able to modify it to some other picture or just text? It's kind of weird to have these emoticons there.

2021-07-05 11:47 UTC, tgodzik commented on docs/editors/overview.md
> -
This break the title below, we need to keep this newline.

2021-07-05 11:47 UTC, tgodzik commented on docs/editors/vscode.md
> -```scala mdoc:requirements
Why is this removed? We should keep it, it's the https://scalameta.org/metals/docs/editors/vscode.html#requirements section.

2021-07-05 12:01 UTC, ckipp01 reviewed
> Thanks for working on this! Looks pretty neat. I have some doubts about:
> O we able to modify it to some other picture or just text? It's kind of weird to have these emoticons there.

So by default that's what they use. I think it's pretty standard as well since when you look around for examples of light/dark mode switches you often see them with a sun and moon icon to notify the user which they are on. Is there something specific about them that you don't like or that worries you?

EDIT:

It looks like you can switch the icons, but I'm unsure what we'd switch them to. https://docusaurus.io/docs/api/themes/configuration#color-mode---dark-mode

2021-07-05 12:07 UTC, tgodzik commented
> So by default that's what they use. I think it's pretty standard as well since when you look around for examples of light/dark mode switches you often see them with a sun and moon icon to notify the user which they are on. Is there something specific about them that you don't like or that worries you?

That's I guess personal preference, it kind of looks like an old communicator icon, so I might be biased because of that.  It's just weird to see emoticons, where they are not needed. Even plain sun/moon would be much better.

![image](https://user-images.githubusercontent.com/3807253/124469145-4824b780-dd9a-11eb-8fcc-b28dd637d65b.png)

This is the one.

2021-07-05 12:08 UTC, ckipp01 commented
> Even plain sun/moon would be much better.

Let me see if I can find two plain icons.

2021-07-05 12:11 UTC, ckipp01 commented
What do you think of this?

![2021-07-05 14 11 24](https://user-images.githubusercontent.com/13974112/124469682-f3357100-dd9a-11eb-9a5e-40140b8d34be.gif)

2021-07-05 12:32 UTC, tgodzik commented
Looks good!

2021-07-05 14:12 UTC, tgodzik approved these changes
LGTM from my side! Tested it locall and everything seems to work.

2021-07-05 15:15 UTC, ckipp01 commented
> LGTM from my side! Tested it locall and everything seems to work.

Cool, I'll wait for another day to see if the others have any input, if now I'll merge away!

2021-07-06 07:14 UTC, merged

2021-07-06 07:59 UTC, ckipp01 commented
Publish failed. Looks like a command isn't found, digging into it now.