Mtags3 - exlucde scala2 depedencies.
scalameta/metals pull request #2971
Opened 2021-07-15 16:45 UTC by dos65

They come transitively from scalameta.
Fixes #2800

2021-07-19 10:17 UTC, tgodzik requested changes
Thanks for figuring this out, I hadn't realised that we had the dependency. Just one small nitpick from my side.

2021-07-19 10:17 UTC, tgodzik commented on build.sbt
> +import org.apache.ivy.core.module.descriptor.ExcludeRule
I think you can remove this one.

2021-07-19 20:23 UTC, dos65 commented on build.sbt
> +import org.apache.ivy.core.module.descriptor.ExcludeRule
:smile: Thx, fixed

2021-07-20 09:11 UTC, tgodzik approved these changes
LGTM!

2021-07-20 09:11 UTC, merged