[Scala3] Fix go to defition for givens
scalameta/metals pull request #3309
Opened 2021-11-23 17:41 UTC by dos65

In semanticdb given is a term if there is no type/using pameters,
otherwise it's a method.
Also, fixes name inference for anonymous givens.

2021-11-24 09:32 UTC, tgodzik requested changes
Thanks for the fix! It seems that a couple of new problems popped up here, or is it expected?

2021-11-24 09:32 UTC, tgodzik commented on tests/unit/src/test/resources/definition-scala3/example/GivenAlias.scala
> +  def doY/*<no file>*/ = "7"
Are w enot indexing the body of given here?
```suggestion
  def doY/*GivenAlias.scala*/ = "7"
```

2021-11-24 09:32 UTC, tgodzik commented on tests/unit/src/test/resources/definition-scala3/example/GivenAlias.scala
> +given [T/*<no file>*/]: Zg/*GivenAlias.scala*/[T/*<no file>*/] with
This shoul be fixed by the current PR, no ?
```suggestion
given [T/*GivenAlias.scala*/]: Zg/*GivenAlias.scala*/[T/*<no file>*/] with
```

2021-11-29 13:58 UTC, dos65 commented on tests/unit/src/test/resources/definition-scala3/example/GivenAlias.scala
> +given `given_Float`/*<no symbol>*/: Float/*Float.scala*/ = 3.0
There is a difference with Scala2 in positions for backquoted ident.
In Scala3 range refers only to name, while in Scala2 it includes backquotes.

I've raised an issue - https://github.com/lampepfl/dotty/issues/14012

2021-11-29 18:21 UTC, tgodzik approved these changes
Looks awesome! I just added one question, but otherwise LGTM

2021-11-29 20:04 UTC, dos65 commented on mtags/src/main/scala/scala/meta/internal/mtags/ScalaMtags.scala
> +          if (!isAlias) {
Thx! I split it onto two different methods. It wasn't fully correct as some non-existing symbols were introduced

2021-11-30 16:00 UTC, tgodzik commented on mtags/src/main/scala/scala/meta/internal/mtags/ScalaMtags.scala
> +          owner
```suggestion
```

this looks unused?

2021-11-30 17:23 UTC, dos65 commented on mtags/src/main/scala/scala/meta/internal/mtags/ScalaMtags.scala
> +          owner
oops! thx!

2021-11-30 17:47 UTC, tgodzik approved these changes
LGTM!

2021-12-01 11:30 UTC, merged