docs: update vim docs to no longer point people to coc-metals
scalameta/metals pull request #3819
Opened 2022-04-12 14:56 UTC by ckipp01

As of this next release
[coc-metals](https://github.com/scalameta/coc-metals) will be officially
deprecated, meaning we shouldn't be pointing people to it in the docs,
and also shouldn't have all the features outlined be coc specific. This
makes those changes.

Note that this is much much more minimal than it previously was. This is
mainly because the docs for `nvim-metals` are pretty spread out, and I
don't have any intention of duplicating them.

- The main docs are in
  https://github.com/scalameta/nvim-metals/blob/main/doc/metals.txt and
  they are in a specific format necessary for Vim help docs.
- https://github.com/scalameta/nvim-metals/discussions/39 holds the
  example configuration
- https://github.com/scalameta/nvim-metals/discussions/279 holds the
  feature list and instructions on how to utilize everything.

All this is mentioned and linked on the vim page.

2022-04-12 14:57 UTC, ckipp01 commented
My plan is to leave this open until we do the next release, and then merge it in right after. I'll wait for https://github.com/scalameta/metals/pull/3816 to be merged and then I'll rebase and update the contributing section with some new info specifically for `nvim-metals` and remove the `coc-metals` stuff there.

2022-04-12 17:46 UTC, ekrich requested changes
I have yet to go through the whole setup process - I started but can give feedback when I get further.

2022-04-12 17:46 UTC, ekrich commented on docs/editors/vim.md
> +Youc an find a full example configuration of these in the [example
```suggestion
You can find a full example configuration of these in the [example
```

2022-04-18 09:50 UTC, ckipp01 commented on docs/editors/vim.md
> +Youc an find a full example configuration of these in the [example
Thanks, fixed!

2022-04-27 00:07 UTC, ckipp01 commented
Now that the release is done is it alright to merge this?

2022-04-27 10:16 UTC, tgodzik approved these changes
LGTM!

2022-04-27 11:39 UTC, merged