Previously, metals saw mill build.sc as ammonite script, now we filte…
scalameta/metals pull request #4106
Opened 2022-07-06 09:39 UTC by jkciesluk

…r it out in isAmmoniteScript so that it's fixed

2022-07-06 10:44 UTC, tgodzik requested changes
Thanks for digging into this! I realized we still have an edge case to cover.

2022-07-06 10:44 UTC, tgodzik commented on mtags/src/main/scala/scala/meta/internal/mtags/CommonMtagsEnrichments.scala
> +      isScalaScript && !isWorksheet && !doc.endsWith("build.sc")
We should accept scripts like `test-build.sc` etc.
```suggestion
      isScalaScript && !isWorksheet && !doc.endsWith("/build.sc")
```

2022-07-06 10:44 UTC, tgodzik commented on mtags/src/main/scala/scala/meta/internal/mtags/CommonMtagsEnrichments.scala
> +      isScalaScript && !isWorksheet && !filename.endsWith("build.sc")
```suggestion
      isScalaScript && !isWorksheet && filename != "build.sc"
```

2022-07-06 12:32 UTC, tanishiking reviewed
Just FYI, this would be a stretch goal, but for more accuracy, it would be great if we can check the build tool is mill by https://github.com/scalameta/metals/blob/d2587f0ef7765180bf1afb783a182ccb03909842/metals/src/main/scala/scala/meta/internal/metals/ammonite/Ammonite.scala#L209-L213
However, it requires a `BuildTool` instance, and it takes more refactoring effort to use it.

Current implementation won't see `build.sc` as ammonite script even if it's not under the mill project.
However, nevermind, it's just a corner case, you don't need to care it :+1:

2022-07-07 09:48 UTC, tgodzik approved these changes
LGTM!

2022-07-07 09:48 UTC, merged