bugfix: Occurence highlight did not work for local vars
scalameta/metals pull request #4109
Opened 2022-07-06 14:18 UTC by jkciesluk

Previously occurrences of `var` in methods as reference and assignment were different, now we have separate logic for them, so that it highlights all occurrences properly

fixes https://github.com/scalameta/metals/issues/4093

2022-07-06 21:37 UTC, kpodsiad approved these changes
Hi @jkciesluk! 
I would add a few sentences of scaladoc for both `findLocalsInScope` and `localVarAlternatives` for future us ;) Otherwise LGTM 💪

2022-07-07 12:21 UTC, tgodzik requested changes
Great work! Thanks for looking into this!

You need to run `sbt scalafixAll` for all the CI checks to pass. It should sort the imports.

2022-07-07 12:21 UTC, tgodzik commented on tests/unit/src/test/scala/tests/DocumentHighlightLspSuite.scala
> +      |    class T1(var <<abc>>: Int) {
Could you add a second class T2 so that we can see if we don't highlight too much.

2022-07-11 13:42 UTC, tgodzik approved these changes
LGTM!

2022-07-11 13:42 UTC, merged