Issue#4154: Add builder for lsp code actions
scalameta/metals pull request #4302
Opened 2022-08-26 10:02 UTC by PeuTit

Avoid repeating code when creating a lsp code action.

Fix issue #4154

2022-08-27 11:17 UTC, kpodsiad requested changes
Thank you for contribution @PeuTit! I left a few small suggestions.

I think we can even move `CodeAction` and `CodeActionProvider` to the `codeactions` package, @tgodzik wdyt?

2022-08-27 11:17 UTC, kpodsiad commented on metals/src/main/scala/scala/meta/internal/metals/codeactions/OrganizeImports.scala
> +            changes = List(path.toURI.toAbsolutePath -> edits),
```suggestion
            changes = List(path-> edits),
```

2022-08-27 11:17 UTC, kpodsiad commented on metals/src/main/scala/scala/meta/internal/metals/codeactions/RewriteBracesParensCodeAction.scala
> +                changes = List(path.toURI.toAbsolutePath -> List(start, end)),
```suggestion
                changes = List(path-> List(start, end)),
```

2022-08-29 05:10 UTC, tanishiking reviewed
Awesome! except @kpodsiad's comments, it looks good to me 😍

2022-08-29 14:41 UTC, kpodsiad requested changes
@PeuTit Could you also change package names in moved files to `scala.meta.internal.metals.codeactions`? You also have to run scalafix -`sbt scalafixAll` to make CI happy ;)

2022-08-30 19:34 UTC, kpodsiad approved these changes
Thank you @PeuTit for your contribution ;)

2022-08-30 19:41 UTC, merged