improvement: Better exhaustive-case completion
scalameta/metals pull request #4831
Opened 2023-01-09 13:34 UTC by jkciesluk

This pr consists of two changes:
1. Previously, exhaustive case completion in 
```scala
List(Option(1)).map{
  cas@@
} // resulted in
List(Option(1)).map{

    case Some(value) => 
    case None =>
      
}
// now results in 
List(Option(1)).map{
  case Some(value) => 
  case None =>
}
```
2. Previously cases in exhaustive-case completion in Scala 3 were not sorted, now we sort them the same way as for exhaustive match

2023-01-09 13:36 UTC, jkciesluk commented
@ckipp01 could you check if the indentation of cases after `exhaustive-case` completion is correct in vim? VS-Code automatically adds indentation so it was hard for me to write good tests for that

2023-01-09 15:48 UTC, ckipp01 commented
> Works _perfect_

![2023-01-09 16 47 59](https://user-images.githubusercontent.com/13974112/211349298-2cd08d31-8838-4533-bd48-98839089f876.gif)

2023-01-12 18:09 UTC, tgodzik requested changes
Great work! I just have some small nitpicks.

2023-01-12 18:09 UTC, tgodzik commented on mtags/src/main/scala-2/scala/meta/internal/pc/completions/MatchCaseCompletions.scala
> +      includeExhaustive: Option[(Boolean, Boolean)] = None
```suggestion
      includeExhaustive: Option[NewLineOptions] = None
```
maybe and additional case class to avoid tuple of booleans?

2023-01-12 18:09 UTC, tgodzik commented on mtags/src/main/scala-3/scala/meta/internal/pc/completions/MatchCaseCompletions.scala
> +      syms: List[(Symbol, A)],
```suggestion
      syms: List[(Symbol, A)],
```
is A needed? Could we instead have a stable class here?

2023-01-16 17:15 UTC, tgodzik approved these changes
LGTM!

2023-01-16 17:15 UTC, merged