bugfix: Insert imports in the correct place in ScalaCLI scripts
scalameta/metals pull request #4940
Opened 2023-02-03 16:29 UTC by tgodzik

Previously, we would expect a file to be a ScalaCLI script if it ended in `.sc`, but that seems to have changed and now it ends in `.sc.scala` similar to ammonite. Now, we adjusted the extension to account for that difference.

Fixes https://github.com/scalameta/metals/issues/4939

2023-02-03 16:30 UTC, tgodzik commented on tests/unit/src/test/scala/tests/codeactions/ScalaCliActionsSuite.scala
> +  check(
This is the new test, the other one was present before.

2023-02-06 08:56 UTC, jkciesluk requested changes
Looks good, just one test is failing

2023-02-06 08:56 UTC, jkciesluk commented on tests/cross/src/test/scala/tests/pc/AutoImportsSuite.scala
> +    filename = "A.sc.scala",
This test seems to be failing on scala 3, because the import gets inserted at the top of the file

2023-02-06 13:20 UTC, jkciesluk approved these changes
LGTM

2023-02-06 14:03 UTC, merged