Force update of scala-debug-adapter by Scala Steward
scalameta/metals pull request #5032
Opened 2023-03-06 16:19 UTC by adpi2

This is an attempt to force Scala Steward to update the scala-debug-adapter version in:
https://github.com/scalameta/metals/blob/34b3cc8f38792be4170344bb4bb685ba15dc3c2a/project/V.scala#L22

It used not to do it because this version was not used in any `libraryDependencies` setting. It was only used in the `buildInfoKeys`:
https://github.com/scalameta/metals/blob/34b3cc8f38792be4170344bb4bb685ba15dc3c2a/build.sbt#L462

2023-03-06 16:28 UTC, lefou commented
I think you need define a new project. Here is an example how it is done in scala-steward project: https://github.com/scala-steward-org/scala-steward/blob/5357f2879b8ea4149ad93c136298a85c380b1942/build.sbt#L259-L269

2023-03-06 16:48 UTC, adpi2 commented
Thanks @lefou! Do you know if there is a way to prevent sbt from creating the `dummy` folder of the `dummy project`?

2023-03-08 09:30 UTC, ckipp01 requested changes
Thanks for the pr! We actually already have a project for this. You can just add `scala-debug-adapter` to `metalsDependencies` here:

https://github.com/scalameta/metals/blob/784494bf7c3f925ffc237a7ef042c5ff0dea6fee/build.sbt#L650-L666

2023-03-08 10:12 UTC, adpi2 commented
> Thanks for the pr! We actually already have a project for this.

Ach, thanks!

2023-03-08 10:27 UTC, adpi2 commented on build.sbt
> +      "ch.epfl.scala" %% "scala-debug-adapter" % V.debugAdapter intransitive (),
Used `intransitive` to avoid the version conflict in transitive dependencies (`scala-parallel-collections`).

2023-03-09 10:15 UTC, ckipp01 approved these changes
Awesome, thanks @adpi2!

2023-03-09 10:15 UTC, merged