docs: Update `architecture.md` after adding support for multi root
scalameta/metals pull request #5209
Opened 2023-05-08 13:58 UTC by kasiaMarek

Update docs after https://github.com/scalameta/metals/pull/5033.

2023-05-11 10:01 UTC, tgodzik requested changes
Thanks for updating this! One small change from me. I think we need to mention MetalsLspService as that is created to actually handle the request

2023-05-11 14:44 UTC, kasiaMarek commented on architecture.md
> +`WorkspaceLspService.scala` is an entrypoint to Metals. This class is responsible for handling LSP [lifecycle messages](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/sp
I felt like that is a bit misleading, since it's not a single instance. Is the current version better?

2023-05-11 15:32 UTC, tgodzik commented on architecture.md
> +`WorkspaceLspService.scala` is an entrypoint to Metals. This class is responsible for handling LSP [lifecycle messages](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/sp
From what I see `WorkspaceLspService` has multiple `MetalsLspService`, no?  I can see only one `WorkspaceLspService` in `MetalsLanguageServer`.

2023-05-12 08:06 UTC, kasiaMarek commented on architecture.md
> +`WorkspaceLspService.scala` is an entrypoint to Metals. This class is responsible for handling LSP [lifecycle messages](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/sp
Oh, sorry, the wording was ambiguous.

2023-05-12 13:29 UTC, tgodzik approved these changes
LGTM!

2023-05-12 13:29 UTC, merged