fix: Make ResetWorkspace more stable
scalameta/metals pull request #5440
Opened 2023-07-13 13:21 UTC by jkciesluk

Now user is asked for confirmation before clearing .bloop directory. 
Adds additional checks for non-existing files, since it used to fail both on `.toList` and `delete`. 
Also, the `ResetWorkspaceLspSuite` was flaky before, now it should work correctly

2023-07-13 13:23 UTC, jkciesluk commented on metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala
> +        .filter(_.exists)
I know it looks weird to check if file exists both here and in `deleteIfExits`, but I saw logs where this method was failing already on `toList`, so maybe it's best to be extra careful

2023-07-14 09:26 UTC, tgodzik requested changes
Some super minor nitpicks, otherwise looks good

2023-07-14 09:26 UTC, tgodzik commented on metals/src/main/scala/scala/meta/internal/metals/Messages.scala
> +      "Are you sure you want to clear bloop directory and reset workspace?"
```suggestion
      "Are you sure you want to clear all caches and compile artifacts and reset workspace?"
```

2023-07-14 09:26 UTC, tgodzik commented on metals/src/main/scala/scala/meta/internal/metals/ClearBloopDir.scala
> +  def apply(workspace: AbsolutePath): Unit = {
```suggestion
object BloopDirs {
  def clear(workspace: AbsolutePath): Unit = {
```

2023-07-14 10:34 UTC, tgodzik approved these changes
LGTM!

2023-07-14 16:08 UTC, merged