Trigger HCR after compilation
scalameta/metals pull request #5578
Opened 2023-08-24 16:01 UTC by iusildra

Follow up of the implementation of hot code replace (HCR) in the scala-debug-adapter and in the vscode extension. Trigger a 2nd compilation (after the first one due to saving) to ensure that HCR does not happen during compilation

2023-08-25 16:49 UTC, tgodzik requested changes

2023-08-25 16:49 UTC, tgodzik commented on metals/src/main/scala/scala/meta/internal/metals/Compilations.scala
> +    val buildTargets: BuildTargets,
```suggestion
    buildTargets: BuildTargets,
```
this shouldn't be needed

2023-08-25 16:49 UTC, tgodzik commented on metals/src/main/scala/scala/meta/internal/metals/Compilations.scala
> +  def compile(
I think you can just add a `compileAll` method based on `recompileAll` without the cleaning and use that. You will need only to add Compilations to the DebugProvider.

2023-08-29 12:50 UTC, iusildra commented
I'll also need to synchronize the `redefineClasses` and `setBreakpoints` commands. Currently, metals send these 2 at the same second, but `setBreakpoint` does not wait for compilation to be finished and breakpoints might not be verified anymore, so the debugger won't stop

2023-08-30 16:46 UTC, tgodzik commented on metals/src/main/scala/scala/meta/internal/metals/debug/DebugProxy.scala
> +        .compile(sourceMapper.buildTargets.allBuildTargetIds)
You can put that into `Compilations` so to not use `buildTargets` from source mapper, but just from Compilations itself.

2024-02-29 08:54 UTC, tgodzik approved these changes
Looks good! Thanks for pushing this forward!

2024-02-29 09:16 UTC, merged