improvement: show bsp as connected after the first message from build server
scalameta/metals pull request #5707
Opened 2023-10-02 12:18 UTC by kasiaMarek

Previously:
 after a no response error, if the build server started responding, we'd have to wait a minute for the status to get fix.

Now: the moment when we get a message from build server we fix the status.

2023-10-04 15:21 UTC, tgodzik requested changes

2023-10-04 15:21 UTC, tgodzik commented on metals/src/main/scala/scala/meta/internal/metals/ServerLivenessMonitor.scala
> +    bspStatus.connected()
```suggestion
    bspStatus.disconnected()
```
? Since this is on shutdown? Seems `disconnected` is not used otherwise?

2023-10-05 10:54 UTC, jkciesluk approved these changes
lgtm

2023-10-05 15:33 UTC, tgodzik approved these changes
LGTM!

2023-10-06 08:28 UTC, merged