improvement: New inlay hints options
scalameta/metals pull request #6236
Opened 2024-03-20 08:57 UTC by jkciesluk

Adds new user configuration for inlay hints, with a fallback to old settings. 

Also adds separate option for inlay hints inside pattern match.

2024-03-26 13:10 UTC, kasiaMarek approved these changes

2024-03-29 11:39 UTC, jkciesluk commented on metals/src/main/scala/scala/meta/internal/metals/UserConfiguration.scala
> +        "inferred-types",
Right, I've missed that. Even `inlay-hints.inferred-types.enable`

2024-03-29 11:40 UTC, jkciesluk commented on mtags/src/main/scala-2/scala/meta/internal/pc/MetalsGlobal.scala
> +        !text.slice(qualEnd, nameStart).contains(".")
The were some false positives, but I don't remember where exactly

2024-04-04 09:31 UTC, tgodzik requested changes

2024-04-04 09:31 UTC, tgodzik commented on mtags/src/main/scala-2/scala/meta/internal/pc/PcInlayHintsProvider.scala
> +      (!vd.rhs.pos.isDefined && params.hintsInPatternMatch()) ||
Could you separate it into different methods? It's a bit unclear what this does check

2024-04-04 09:31 UTC, tgodzik commented on tests/unit/src/main/scala/tests/BaseInlayHintsExpectSuite.scala
> +            false,
I would set it to true as default

2024-04-04 14:33 UTC, tgodzik approved these changes
LGTM!

2024-04-04 14:45 UTC, merged