improvement: Specifically choose which targets to compile
scalameta/metals pull request #6639
Opened 2024-07-26 14:00 UTC by tgodzik

Previously, we would wait for full compilation for debugger and scalafix, however that is not needed, we only need to compile the current target in that case.

Now, we specify it explicitly.

The change is really small, ignore whitespaces option will show it.

2024-07-30 09:50 UTC, kasiaMarek requested changes

2024-07-30 09:50 UTC, kasiaMarek commented on metals/src/main/scala/scala/meta/internal/metals/Compilations.scala
> +      compileDependencies: Boolean,
```suggestion
      compileInverseDependencies: Boolean,
```

2024-07-30 14:26 UTC, tgodzik commented on metals/src/main/scala/scala/meta/internal/metals/Compilations.scala
> +      compileDependencies: Boolean,
done!

2024-08-01 09:15 UTC, kasiaMarek approved these changes

2024-08-05 11:34 UTC, merged