feat: implement 'convert to named lambda parameters' code action
scalameta/metals pull request #6669
Opened 2024-08-12 15:19 UTC by KacperFKorban

Add a code action that converts a wildcard lambda to a lambda with named parameters. It supports Scala 3 only at the moment.

e.g.
![converttonamedlambdaparameters](https://github.com/user-attachments/assets/93561630-b626-4cff-8248-806e4c32744a)
![converttonamedlambdaparameters1](https://github.com/user-attachments/assets/292ad14f-be8b-4535-b4e4-45819f14da9e)

Disclaimer: I'm not sure what I'm doing :smiley:

2024-08-13 11:21 UTC, tgodzik commented
I wonder if we need to add a new method for this. Ideally each new code action feature would be able to reuse an existing method. Would it possible to implements it with the scalameta parser only? We could use go to type definition on wildcards to obtain its type symbol and construct a new out of it.

Alternatively, we could add a more universal method such as (ActionType interface should be binary compatible I think :thinking: otherwise we can use a string and some separate config parameter)
```scala
CompletableFuture<List<TextEdit>> codeAction(OffsetParams params, ActionType actionType) {
```

Adding a new method for each code action causes the interfaces to bloat and more complex to the users, which is why I am hesitant to continue with that.

2024-08-13 15:41 UTC, KacperFKorban commented
Using only the scalameta parser would be ideal, but my concern is that it isn't that obvious how to find the reference of the correct wildcard parameter. With `pc`, I can just use the parameter symbol. I'll try to reimplement it using just trees and we'll see how it goes.

2024-08-13 15:46 UTC, tgodzik commented
> but my concern is that it isn't that obvious how to find the reference of the correct wildcard parameter

There is only one, no? Not sure if I understand :thinking:

2024-08-13 15:52 UTC, KacperFKorban commented
I mean that there could be multiple wildcard params for one lambda and there can be nested wildcard lambdas. Plus the rules for resolving a wildcard param into its owning lambda are not 100% clear to me. In `pc` I can reference the parameters of a lambda and use their symbols, because it is already done in the Scala compiler's parser. But the tree representing a wildcard lambda in scalameta is just a node `AnonymousFunction` with a single field -- `body`.

2024-08-13 15:59 UTC, tgodzik commented
Ach, if it's more difficult with the scalameta parser then do not worry about that. I would however try to add a more universal interface for code actions

2025-05-05 08:22 UTC, kasiaMarek requested changes

2025-05-05 08:22 UTC, kasiaMarek commented on metals/src/main/scala/scala/meta/internal/metals/codeactions/ConvertToNamedLambdaParameters.scala
> +  override def handleCommand(
You should rather use `resolveCodeAction`, using `handleCommand` is an outdated way to do this. See: https://github.com/scalameta/metals/pull/6978

2025-05-06 08:05 UTC, kasiaMarek approved these changes
lgtm

2025-05-06 14:48 UTC, merged