improvement: queue or cancel previous connect request
scalameta/metals pull request #6691
Opened 2024-08-19 15:15 UTC by kasiaMarek

2024-08-20 14:53 UTC, kasiaMarek commented on tests/slow/src/test/scala/tests/sbt/SbtBloopLspSuite.scala
> +          progressMessage,
We don't deduplicate like this anymore. Instead requests will be queued and the first one will get cancelled. So `sbt bloopInstall` will be executed twice, and the first request will be cancelled after that, so `import` and `indexing` are executed only once.

2024-09-17 09:24 UTC, tgodzik commented on metals/src/main/scala/scala/meta/internal/metals/ConnectionProvider.scala
> +          request.cancelCompare(iter.next().request) match {
Could you explain the logic a bit better here? Could we use some case objects instead of just numbers?

2024-09-17 09:27 UTC, tgodzik requested changes

2024-09-17 09:27 UTC, tgodzik commented on metals/src/main/scala/scala/meta/internal/metals/Interruptable.scala
> +    cancelPromise: Promise[Unit],
Are we able to forward the cancel request to an underlying process if for example bloopInstall is running?

2025-01-08 16:58 UTC, tgodzik reviewed
Looks good overall! I like how clear the code is. Is it ready to stop being a draft?

2025-02-18 17:32 UTC, tgodzik commented on metals/src/main/scala/scala/meta/internal/metals/ConnectionProvider.scala
> +      case _: Disconnect => Queue
If we have a Disconnect then we should probably Yield, no? There is no sense to run idnexing after disconnecting?

2025-02-18 17:32 UTC, tgodzik commented on metals/src/main/scala/scala/meta/internal/metals/ConnectionProvider.scala
> +      case _: Disconnect => Queue
Same here if we have Disconnect, we should probably just cancel everything and not lose time on import.

2025-03-11 15:12 UTC, tgodzik commented
I don't see any changes since last time, did you forget to push them or my comments were not valid?

2025-03-11 16:32 UTC, tgodzik approved these changes
LGTM!

2025-05-07 08:37 UTC, merged