improvement: Make including detail in completion label configurable
scalameta/metals pull request #6986
Opened 2024-11-29 02:26 UTC by Sorixelle

Some LSP clients (such as Emacs using Eglot and Corfu) use the label field to insert a completion if completionItem/resolve has not returned by the time the completion is selected. Including the contents of the detail property in the label causes it to be included in the file itself in these clients. To remedy this, we define a isDetailIncludedInLabel option under compilerOptions to make this behaviour toggleable. We also disable this behaviour by default in Emacs, since this is where the undesirable behaviour was located.

TODO:
- [ ] Testing (unsure what tests should be added - please let me know where they should go)

Fixes #6849.

2024-11-29 06:11 UTC, Sorixelle commented
Seems like the changes to `MetalsServerConfig.default` don't get applied to Scala 3.3.4 projects. Tested with a Mill project using 3.3.4 and the option is not automatically applied - I need to configure my editor to set it explicitly during the `initialize` command. Unsure why this is the case - any pointers?

2024-11-29 09:42 UTC, tgodzik commented
> EDIT: Some investigation leads me to believe that Metals is falling back to the Scala presentation compiler instead of mtags. Unsure if there's anything that can be done about that until mtags is updated for 3.3.4.

From 3.3.4 onwards we use mtags published by the compiler itself to avoid having to publish it to every version of the compiler.

2024-11-29 14:25 UTC, tgodzik commented
Ach, and we usually just port them ourselves, so no need to worry about it

2024-11-29 14:28 UTC, tgodzik commented on mtags-interfaces/src/main/java/scala/meta/pc/PresentationCompilerConfig.java
> +	boolean isDetailIncludedInLabel();
This should have a default to avoid MiMa failing

2024-11-29 14:29 UTC, tgodzik requested changes
Looks good aside from the MiMa failure :tada:

2024-11-29 18:07 UTC, Sorixelle commented
Addressed the default - are we sure this change doesn't require any tests? I'd add them, I'm just not sure where they belong.

2024-12-01 19:37 UTC, tgodzik commented
> Addressed the default - are we sure this change doesn't require any tests? I'd add them, I'm just not sure where they belong.

You should be able to add the tests to the cross module, you would need to change the config like in https://github.com/scalameta/metals/blob/main/tests/cross/src/test/scala/tests/pc/CompletionSnippetNegSuite.scala#L10

2024-12-02 20:44 UTC, Sorixelle commented
That should do for test cases - let me know if there's anything else you think I should check.

2024-12-05 16:51 UTC, tgodzik commented
> That should do for test cases - let me know if there's anything else you think I should check.

I added one test, fixed the added one on Scala 3 and removed the detail also from scope completions. Thanks for working on this!

2024-12-05 16:51 UTC, tgodzik approved these changes
LGTM

I will merge tomorrow once it passes (unless I broke something)

2024-12-06 11:52 UTC, merged